# Generated by Django 4.0.3 on 2022-04-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_paragraphentries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphentries',
            name='paragraph',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
