# Generated by Django 4.0.3 on 2022-04-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_remove_project_image_remove_project_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIdeas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=1000, null=True)),
                ('due_date', models.DateField()),
                ('estimated_hours', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
            ],
        ),
    ]
