# Generated by Django 4.0.3 on 2022-04-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_projectideas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParagraphEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('paragraph', models.TextField(max_length=1000, null=True)),
                ('source', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
