# Generated by Django 4.0.3 on 2022-04-26 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_alter_paragraphentries_paragraph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParagraphEntries',
        ),
    ]
